services:
  app:
    image: node:24.2-slim
    tty: true
    stdin_open: true
    environment:
      - WATCHPACK_POLLING=true
    working_dir: /app
    #restart: always
    volumes:
      - ./src:/app
      - node_modules:/app/node_modules
      - next:/app/.next
    ports:
      - '3000:3000'
    command: sh -c "npm install && npm update && npm run dev"
volumes:
  node_modules:
  next:
