import fs from "node:fs";
import path from "node:path";
import { extractToc, renderMarkdown, renderPlain } from "@ivecolor/markdown";
import { loadSiteData, PAGE_NAME_IDS, WORKS_TAG } from "./site-data.mjs";
import { writeFeeds } from "./generate-feeds.mjs";

/**
 * CMS の配信データ（`/export/build.json`）から、ページが読む1つのモジュールを吐く。
 *
 * **描画はここで1回だけ**やる。ページ側で描くと同じ本文を何度も通すことになり、
 * `@ivecolor/markdown` を Next のバンドルに入れる必要も出る。
 * このスクリプトは素の Node で動き、TypeScript のまま読める（Node 22.18+ の型除去）。
 *
 * `src/posts/*.md` と `src/works/*.md` はもう読まない。記事の正本は CMS 側の D1。
 */

function readJsonFile(absolutePath) {
  return JSON.parse(fs.readFileSync(absolutePath, "utf8"));
}

/** ISO 8601 の新しい順。null は最後 */
function byPublishedDesc(a, b) {
  return (b.published_at ?? "").localeCompare(a.published_at ?? "");
}

/**
 * 作品の並び順は `meta.order` の小さい順。
 * **`meta` の値は文字列で届く**ので数として使うときに変換する（契約の `meta`）。
 */
function byOrder(a, b) {
  const left = Number(a.order);
  const right = Number(b.order);
  if (Number.isFinite(left) && Number.isFinite(right) && left !== right) return left - right;
  if (Number.isFinite(left) !== Number.isFinite(right)) return Number.isFinite(left) ? -1 : 1;
  return byPublishedDesc(a, b);
}

/** 一覧カードに要るぶんだけ。本文とHTMLは持たせない（生成物が倍になる）*/
function toSummary(record) {
  const { contentHtml, toc, ...rest } = record;
  return rest;
}

async function toRecord(post, ctx, tagsById) {
  const meta = post.meta ?? {};
  return {
    slug: post.name_id,
    title: post.title,
    summary: post.summary,
    image: post.thumbnail_url,
    // 作品のロゴ。`/m/{id}` で書かれた値は CMS が配信URLに直して渡す
    icon: typeof meta.icon === "string" ? meta.icon : null,
    order: meta.order ?? null,
    publishedAt: post.published_at,
    editedAt: post.edited_at,
    featured: post.featured === true,
    tags: (post.tag_ids ?? [])
      .map((id) => tagsById[id])
      .filter(Boolean)
      // 印として使うタグはタグ一覧に出さない（契約の「予約タグ」）
      .filter((tag) => tag.name_id !== WORKS_TAG)
      .map((tag) => ({ slug: tag.name_id, name: tag.name })),
    contentHtml: await renderMarkdown(post.content_md, ctx),
    toc: extractToc(post.content_md),
    // RSS と og:description に使う。要約が無ければ本文の頭を使う
    plain: (post.summary || renderPlain(post.content_md)).slice(0, 200),
  };
}

function indexBySlug(records) {
  return Object.fromEntries(records.map((record) => [record.slug, record]));
}

function writeGeneratedModule({ rootDir, outputRelativePath, data }) {
  const absoluteOutputPath = path.join(rootDir, outputRelativePath);
  fs.mkdirSync(path.dirname(absoluteOutputPath), { recursive: true });

  const source =
    "// This file is auto-generated by scripts/generate-content.mjs\n" +
    "// Do not edit manually.\n\n" +
    `export const generatedContent = ${JSON.stringify(data)};\n` +
    "export default generatedContent;\n";

  fs.writeFileSync(absoluteOutputPath, source, "utf8");
  console.log(`Generated ${outputRelativePath}`);
}

async function main() {
  const rootDir = process.cwd();
  const data = await loadSiteData();

  const tagsById = Object.fromEntries((data.tags ?? []).map((tag) => [tag.id, tag]));
  const worksTagId = (data.tags ?? []).find((tag) => tag.name_id === WORKS_TAG)?.id ?? null;

  // **記事と固定ページは同じ `posts` に入っていて、`status` でしか分かれない。**
  // ここを `published` だけで絞ると固定ページが1件も残らない
  const published = (data.posts ?? []).filter((p) => p.status === "published");
  const specific = (data.posts ?? []).filter((p) => p.status === "specific");

  const isWork = (post) => worksTagId !== null && (post.tag_ids ?? []).includes(worksTagId);

  const ctx = {
    posts: Object.fromEntries(
      published.map((p) => [
        p.name_id,
        {
          slug: p.name_id,
          title: p.title,
          summary: p.summary,
          thumbnailUrl: p.thumbnail_url,
          publishedAt: p.published_at,
          editedAt: p.edited_at,
        },
      ]),
    ),
    siteUrl: data.site?.url || "https://kisana.me",
  };

  const render = (posts) => Promise.all(posts.map((post) => toRecord(post, ctx, tagsById)));

  const posts = (await render(published.filter((p) => !isWork(p)))).sort(byPublishedDesc);
  const works = (await render(published.filter(isWork))).sort(byOrder);
  const pages = await render(specific.filter((p) => PAGE_NAME_IDS.includes(p.name_id)));

  // 記事が付けているタグだけ。1件も付いていないタグは一覧に出さない
  const used = new Set(posts.flatMap((post) => post.tags.map((tag) => tag.slug)));
  const tags = (data.tags ?? [])
    .filter((tag) => tag.name_id !== WORKS_TAG && used.has(tag.name_id))
    .map((tag) => ({ slug: tag.name_id, name: tag.name, description: tag.description }));

  const generated = {
    site: {
      name: data.site?.name ?? "KISANA:ME",
      description: data.site?.description ?? "",
      url: ctx.siteUrl,
    },
    generatedAt: data.generated_at ?? null,
    home: {
      exhibitsData: readJsonFile(path.join(rootDir, "data", "home", "exhibits.json")),
      projectsData: readJsonFile(path.join(rootDir, "data", "home", "projects_data.json")),
    },
    posts: { list: posts.map(toSummary), bySlug: indexBySlug(posts) },
    works: { list: works.map(toSummary), bySlug: indexBySlug(works) },
    pages: indexBySlug(pages),
    tags,
  };

  writeGeneratedModule({
    rootDir,
    outputRelativePath: path.join("generated", "content.generated.js"),
    data: generated,
  });

  writeFeeds({ rootDir, generated });
}

await main();
