import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";
import hljs from "highlight.js";

import MarkdownIt from "markdown-it";
import markdownItContainer from "markdown-it-container";
import markdownItMark from "markdown-it-mark";
import markdownItIns from "markdown-it-ins";
import markdownItAbbr from "markdown-it-abbr";
import markdownItDeflist from "markdown-it-deflist";
import markdownItSup from "markdown-it-sup";
import markdownItSub from "markdown-it-sub";
import markdownItFootnote from "markdown-it-footnote";
import markdownItMultimdTable from "markdown-it-multimd-table";
import markdownItToc from "markdown-it-table-of-contents";
import markdownItTaskLists from "markdown-it-task-lists";

function readJsonFile(absolutePath) {
  const fileContents = fs.readFileSync(absolutePath, "utf8");
  return JSON.parse(fileContents);
}

function safeDateValue(value) {
  const date = new Date(value);
  return Number.isFinite(date.getTime()) ? date.getTime() : 0;
}

function createMarkdownRenderer() {
  // Note: the highlight callback references `md` (assigned after ctor).
  // This matches the pattern already used in the codebase.
  let md;
  md = new MarkdownIt({
    highlight: function (str, lang) {
      if (lang && hljs.getLanguage(lang)) {
        try {
          return (
            '<pre class="hljs"><span>lang:' +
            lang +
            '</span><br /><code>' +
            hljs.highlight(str, { language: lang, ignoreIllegals: true }).value +
            "</code></pre>"
          );
        } catch {
          // fallthrough
        }
      }
      return '<pre class="hljs"><code>' + md.utils.escapeHtml(str) + "</code></pre>";
    },
    html: true,
    linkify: true,
    breaks: true,
    typographer: true,
  })
    .use(markdownItMark)
    .use(markdownItIns)
    .use(markdownItAbbr)
    .use(markdownItDeflist)
    .use(markdownItSup)
    .use(markdownItSub)
    .use(markdownItFootnote)
    .use(markdownItContainer, "info")
    .use(markdownItContainer, "success")
    .use(markdownItContainer, "warning")
    .use(markdownItContainer, "danger")
    .use(markdownItMultimdTable, {
      multiline: true,
      rowspan: true,
      headerless: true,
    })
    .use(markdownItToc, {
      transformLink: () => "",
      containerHeaderHtml: '<div class="toc-container-header">目次</div>',
    })
    .use(markdownItTaskLists);

  return md;
}

function loadMarkdownDirectory({ rootDir, relativeDir, markdown }) {
  const absoluteDir = path.join(rootDir, relativeDir);
  const fileNames = fs.readdirSync(absoluteDir).filter((name) => name.endsWith(".md"));

  const bySlug = {};
  const meta = [];

  for (const fileName of fileNames) {
    const slug = fileName.replace(/\.md$/, "");
    const absolutePath = path.join(absoluteDir, fileName);
    const raw = fs.readFileSync(absolutePath, "utf8");
    const parsed = matter(raw);
    const contentHtml = markdown.render(parsed.content).toString();

    const record = {
      slug,
      id: slug,
      contentHtml,
      ...parsed.data,
    };

    bySlug[slug] = record;
    meta.push({ slug, ...parsed.data });
  }

  return { bySlug, meta };
}

function writeGeneratedModule({ rootDir, outputRelativePath, data }) {
  const absoluteOutputPath = path.join(rootDir, outputRelativePath);
  fs.mkdirSync(path.dirname(absoluteOutputPath), { recursive: true });

  const source =
    "// This file is auto-generated by scripts/generate-content.mjs\n" +
    "// Do not edit manually.\n\n" +
    `export const generatedContent = ${JSON.stringify(data)};\n` +
    "export default generatedContent;\n";

  fs.writeFileSync(absoluteOutputPath, source, "utf8");
  // eslint-disable-next-line no-console
  console.log(`Generated ${outputRelativePath}`);
}

function main() {
  const rootDir = process.cwd();
  const markdown = createMarkdownRenderer();

  const homeExhibits = readJsonFile(path.join(rootDir, "data", "home", "exhibits.json"));
  const homeProjects = readJsonFile(path.join(rootDir, "data", "home", "projects_data.json"));
  const series = readJsonFile(path.join(rootDir, "data", "series.json"));

  const postsLoaded = loadMarkdownDirectory({
    rootDir,
    relativeDir: "posts",
    markdown,
  });

  const worksLoaded = loadMarkdownDirectory({
    rootDir,
    relativeDir: "works",
    markdown,
  });

  const postsSortedDate = postsLoaded.meta
    .slice()
    .sort((a, b) => safeDateValue(b.date) - safeDateValue(a.date));

  const postsSortedUpdate = postsLoaded.meta
    .slice()
    .sort((a, b) => safeDateValue(b.update) - safeDateValue(a.update));

  const worksSorted = worksLoaded.meta
    .slice()
    .sort((a, b) => (a.order ?? 0) - (b.order ?? 0));

  const generated = {
    home: {
      exhibitsData: homeExhibits,
      projectsData: homeProjects,
    },
    series,
    posts: {
      bySlug: postsLoaded.bySlug,
      sortedDate: postsSortedDate,
      sortedUpdate: postsSortedUpdate,
      slugs: Object.keys(postsLoaded.bySlug),
    },
    works: {
      bySlug: worksLoaded.bySlug,
      sorted: worksSorted,
      slugs: Object.keys(worksLoaded.bySlug),
    },
  };

  writeGeneratedModule({
    rootDir,
    outputRelativePath: path.join("generated", "content.generated.js"),
    data: generated,
  });
}

main();
